name: ptm-env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # 基础系统依赖
  - python=3.10
  - pip
  - openssl
  - libgcc-ng
  - libstdcxx-ng
  
  # GPU相关依赖
  - cudatoolkit=11.8
  - cudnn

  # 科学计算核心
  - numpy
  - scipy
  - pandas
  - h5py

  - pytorch=2.0

  # 生物信息学相关
  - biopython
  - biotite
  
  - pip:
    - tensorflow=2.15
    - tensorflow-addons
    - fair-esm
    - scikit-learn>=1.6.1
    - imbalanced-learn>=0.13.0
    - matplotlib>=3.10.3
    - seaborn>=0.13.2
    - tqdm>=4.67.1
    - joblib>=1.4.2
    - logomaker>=0.8.7
